version: '2.0'
services:
  mysql_master:
    image: mysql:5.7.22
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - $PWD/mysql_data:/var/lib/mysql
