version: '2.0'

services:
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - $PWD/redis_data:/bitnami/redis/data

volumes:
  redis_data:
    driver: local
